# ============================================================================
# AchievementCatalog — 成就 UI 展示数据（LocalAchievementsPlugin 对齐）
# ============================================================================
# 数据来源：LocalAchievementsPlugin.RegisterCustomAchievement
# 编号与图标文件一一对应：资产/成就/<编号>.png
# ============================================================================

class_name AchievementCatalog
extends RefCounted

## 没有单独图标时使用的默认成就图标（复用现有 UI 圆形资源）。
const DEFAULT_ICON := "res://资产/UI/战争/圆圈.png"

## 有序列表。number 对应 LocalAchievementsPlugin 的成就编号；title/desc 为实际名称与描述。
const LIST: Array[Dictionary] = [
	{
		"number": 0, "title": "漫长的革命",
		"desc": "层层险阻，烈火熔炼。冲破重压，照耀人间\n比任何时候都更接近那崇高的理想",
		"icon": "res://资产/成就/0.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 1, "title": "从天上到人间来！",
		"desc": "金珠玛米从来没有这么具体过……\n曾经是不可能的事情",
		"icon": "res://资产/成就/1.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 2, "title": "一步迈进共产主义",
		"desc": "更接近崇高的理想\n社会主义的终极阶段",
		"icon": "res://资产/成就/2.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 3, "title": "毛主义的坚实壁垒",
		"desc": "我们走在大路上\n枪杆子里出政权",
		"icon": "res://资产/成就/3.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 4, "title": "遗产保卫者",
		"desc": "拨开了迷雾前途是多么辉煌，解放了思想道路多么宽广\n毛泽东主席为我们指出了幸福路",
		"icon": "res://资产/成就/4.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 5, "title": "向世界开放",
		"desc": "你办事，我放心\n有问题找谁来着？",
		"icon": "res://资产/成就/5.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 6, "title": "海德公园社会主义",
		"desc": "“我相信民主，因为它释放了每个人生命的能量。”\n必要不充分条件",
		"icon": "res://资产/成就/6.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 7, "title": "大胆去闯荡",
		"desc": "社会主义和市场经济之间不存在根本的矛盾”\n我们所经历的……",
		"icon": "res://资产/成就/7.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 8, "title": "新绝对真理",
		"desc": "“如果那个说用坦克压下去””\nEVERYTHING IS *** FINE",
		"icon": "res://资产/成就/8.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 9, "title": "亚洲民主",
		"desc": "“只要台湾在手，共产党就无可奈何””\n“什么叫对面也投美了”",
		"icon": "res://资产/成就/9.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 10, "title": "权力意志",
		"desc": "君主必须要像狮子一样凶残，像狐狸一样狡猾\n当代秦始皇",
		"icon": "res://资产/成就/10.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 11, "title": "大号朝鲜民主主义人民共和国",
		"desc": "由于我们对人民的信任，我们赢得了一切\n谁又失去了一切呢？",
		"icon": "res://资产/成就/11.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 12, "title": "亚洲的皮诺切特",
		"desc": "有时民主需用鲜血灌溉\n即便它只是叫做“民主”",
		"icon": "res://资产/成就/12.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 13, "title": "屠龙者",
		"desc": "活出你的一生吧，给予他人快乐吧，但请仔细听好我说的一切。只要\n我们活着，你就胜利了，因为你活在人民的心中！\n你所开创的“民主大业”终究被抛弃了",
		"icon": "res://资产/成就/13.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 14, "title": "天命尽失",
		"desc": "搞砸了一切\n失去一切你可以失去的",
		"icon": "res://资产/成就/14.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 15, "title": "火，诗人和残酷行动纲领",
		"desc": "火便是你，火便是我。火便是他，火便是火。——《凤凰涅槃》\n一切社会革命的匪徒呀，万岁万岁万岁！",
		"icon": "res://资产/成就/15.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 16, "title": "永远的革命",
		"desc": "再武装的先知\n打倒修正者，救出马克思",
		"icon": "res://资产/成就/16.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 17, "title": "没头脑与不高兴",
		"desc": "笑到最后……？\n相同的过程，不同的结果",
		"icon": "res://资产/成就/17.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 18, "title": "没有人写信的上校",
		"desc": "领袖所需要的不是聪慧，财富，暴力、而是被发自内心的崇拜与敬仰\n你已经拿起了第一块餐巾",
		"icon": "res://资产/成就/18.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 19, "title": "第二代满铁马克思主义的黎明",
		"desc": "我等精锐威武无比，盟邦之民得以安心\n等等，这首歌唱的是谁？",
		"icon": "res://资产/成就/19.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 20, "title": "共和国内当奥古斯都",
		"desc": "新时代皇帝\n有传闻说……",
		"icon": "res://资产/成就/20.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 21, "title": "东方赛博朋克",
		"desc": "接管一切\n引火烧身",
		"icon": "res://资产/成就/21.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 22, "title": "国家统一",
		"desc": "新疆、西藏、港澳台与藏南皆在祖国怀抱。\n从此地图不再有争议了",
		"icon": "res://资产/成就/22.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 23, "title": "新十月",
		"desc": "让毛派在前苏联取得胜利！\n回归苏联最初的理想",
		"icon": "res://资产/成就/23.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 222, "title": "毛主席逝世",
		"desc": "一个时代结束了。\n拔锚起航！",
		"icon": "res://资产/成就/222.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 666, "title": "归来之人",
		"desc": "祂已归来，我们无处可逃……\n一个幽灵复活",
		"icon": "res://资产/成就/666.png",
		"source": "LocalAchievementsPlugin",
	},
	{
		"number": 24,
		"title": "死亡天使",
		"desc": "送44位政客命定之死",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 25,
		"title": "乒乓外交",
		"desc": "单局游戏中被禁运7次。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 27,
		"title": "打住！",
		"desc": "促使苏联出兵匈牙利和波兰。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 28,
		"title": "民主",
		"desc": "在落实多党制，开放公民权的情况下送总理、军委主席与外交部长上西天，并派军队去首都示威。显然，这就是人民的名义。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 30,
		"title": "革命万岁",
		"desc": "文化大革命必须年年讲、月月讲、天天讲。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 32,
		"title": "大号阿尔巴尼亚",
		"desc": "国家体制为威权主义，同时遭受美苏禁运，失去所有势力范围。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 33,
		"title": "超级大国",
		"desc": "中国已然成为世界上最具影响力的政治实体！",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 35,
		"title": "光辉未来",
		"desc": "中苏两国均属同一政治集团，且皆引入了自动化经济。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 36,
		"title": "变革之风",
		"desc": "人人都爱戈比。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 37,
		"title": "牢不可破的传统",
		"desc": "发达社会主义自然保护区。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 38,
		"title": "前所未有的强大",
		"desc": "一种理念，两条路径。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 39,
		"title": "和平缔造者",
		"desc": "解决中印领土争端。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 41,
		"title": "亚洲皮诺切特",
		"desc": "有时民主需用鲜血灌溉。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 42,
		"title": "亚洲民主",
		"desc": "只要台湾在手，共产党就永无翻身之地。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 43,
		"title": "大号朝鲜",
		"desc": "大号朝鲜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 44,
		"title": "大胆去闯荡",
		"desc": "社会主义与市场经济之间不存在根本矛盾。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 45,
		"title": "向世界开放",
		"desc": "你办事，我放心。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 46,
		"title": "毛主义的坚实壁垒",
		"desc": "枪杆子里出政权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 47,
		"title": "圣人之梦",
		"desc": "建成小康社会。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 48,
		"title": "勃列日涅夫式的幸福",
		"desc": "好东西不过是被遗忘的老东西",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 49,
		"title": "一千亿还不够？",
		"desc": "古中国掌管杀伐的神明",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 50,
		"title": "问题解决了",
		"desc": "实现朝鲜和平统一。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 51,
		"title": "朝鲜危机",
		"desc": "一家独大。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 52,
		"title": "难学易斗",
		"desc": "在“造反有理”难度下完成游戏。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 53,
		"title": "跟着毛主席，在大风大浪中前进",
		"desc": "在“浩荡文革”难度下完成游戏。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 54,
		"title": "永恒火焰",
		"desc": "让毛派起义者取得阿富汗内战胜利。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 55,
		"title": "涅槃重生",
		"desc": "新兴毛派政党夺得大选胜利。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 56,
		"title": "天命尽失",
		"desc": "在生活水平低于10，国际影响力低于5，边疆地区尽失的情况下以自由化姿态取得游戏“胜利”。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 58,
		"title": "一步迈进共产主义",
		"desc": "采用自动化经济，生活水平高于70，腐败为0，实行一党制的同时彻底放开公民自由。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 59,
		"title": "用刀叉吃饭",
		"desc": "将胡耀邦推上领袖宝座，实行自由主义，交好美国，且生活水平高于80。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 60,
		"title": "东方赛博朋克",
		"desc": "实行威权主义，党内路线为威权，采用自动化经济，完成军事与特勤研究，让中国领袖兼任总理与军委主席，军备与特勤投资高于39，自由化倾向为0。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 61,
		"title": "叶戈尔，你错了",
		"desc": "试着向右拐（哪怕只要一次）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 62,
		"title": "猛虎经济体",
		"desc": "在1980年前实现工农业双产超70的目标。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 63,
		"title": "十亿人民",
		"desc": "1980年前人口达到10亿。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 64,
		"title": "直到胜利，直到胜利，直到耶路撒冷",
		"desc": "建立亲中伊拉克。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 65,
		"title": "兄弟情谊与团结",
		"desc": "拯救南斯拉夫！",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 66,
		"title": "一国两制",
		"desc": "采用和平手段，让台湾回归祖国！",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 67,
		"title": "树欲静而风不止",
		"desc": "让中国政治集团的规模超越华约（至少有8个成员）",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 68,
		"title": "这是一场大规模的运动",
		"desc": "让中国政治集团的规模超越北约（至少有14个成员）",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 74,
		"title": "百家争鸣",
		"desc": "在新精英政治体制内建立派系一党民主。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 75,
		"title": "儒学",
		"desc": "确立儒家思想在新精英政治中的主导地位。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 76,
		"title": "法家",
		"desc": "确立法家思想在新精英政治中的主导地位。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 77,
		"title": "亚洲罗马",
		"desc": "在新精英政治内建立军事民主。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 78,
		"title": "台湾省",
		"desc": "解放台湾！",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 79,
		"title": "新十月",
		"desc": "毛主义在前苏联取得了胜利！",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 80,
		"title": "工人统一战线",
		"desc": "达成印度结局 #1。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 81,
		"title": "美式开局",
		"desc": "达成印度结局 #2。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 82,
		"title": "三方和谐",
		"desc": "达成印度结局 #3。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 83,
		"title": "永恒斗争",
		"desc": "达成印度结局 #4。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 84,
		"title": "临时过渡",
		"desc": "达成印度结局 #5。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 85,
		"title": "共产国际的人",
		"desc": "复兴王明的遗产。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 86,
		"title": "指挥官同志的遗赠",
		"desc": "所有南美国家皆加入中国势力范围。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 87,
		"title": "软实力",
		"desc": "所有南美国家通过事件变得亲华。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 88,
		"title": "变了吗？",
		"desc": "坦克雷多·内维斯成为巴西总统。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 89,
		"title": "庇隆万岁！",
		"desc": "让极左翼庇隆主义者在阿根廷掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 90,
		"title": "期待已久的胜利",
		"desc": "西拉斯终于能在玻利维亚实施他的改革。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 91,
		"title": "用路易斯·科尔瓦兰换掉恶霸",
		"desc": "在智利发动社会主义革命。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 92,
		"title": "这真的是保守主义吗？",
		"desc": "阿尔贝托·苏马兰在乌拉圭掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 93,
		"title": "解放神学",
		"desc": "让解放神学支持者在巴拉圭掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 94,
		"title": "开辟光辉革命之路",
		"desc": "在秘鲁发动毛主义革命。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 95,
		"title": "妥协政策",
		"desc": "安赫尔·杜阿尔特成为厄瓜多尔总统。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 96,
		"title": "第二个保守任期",
		"desc": "贝坦库尔在哥伦比亚连任。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 97,
		"title": "哥伦比亚乱炖",
		"desc": "纳瓦罗在哥伦比亚发动政变。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 98,
		"title": "查韦斯：人民之心",
		"desc": "让查韦斯在委内瑞拉提前掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 99,
		"title": "疑心被证实是错的",
		"desc": "贾根在圭亚那连任。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 100,
		"title": "这真的是毛主义吗？",
		"desc": "本恩在圭亚那建立了独裁统治。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 101,
		"title": "第二个合作社",
		"desc": "苏里南宣布自己为合作共和国。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 102,
		"title": "天上的奶酪",
		"desc": "我们登上了月球。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 103,
		"title": "快于二十一世纪",
		"desc": "国际空间站。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 104,
		"title": "红色星球",
		"desc": "我们登上了火星。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 105,
		"title": "埋葬仇恨",
		"desc": "日本君主制终结。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 106,
		"title": "新的旧时代",
		"desc": "日本觉醒了。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 107,
		"title": "新时代天皇",
		"desc": "有传言说...",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 108,
		"title": "回到乡村",
		"desc": "超越极限！",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 109,
		"title": "忆苦思甜",
		"desc": "蒙古和中国统一。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 110,
		"title": "一带一路",
		"desc": "下列所有国家亲华并在我们的经济联盟中：埃及、以色列、伊拉克、伊朗、巴基斯坦、阿富汗、印度、孟加拉国、蒙古。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 111,
		"title": "紫禁城",
		"desc": "中国由以下统治者统治过：华国锋、邓小平、陈云、王明的亲戚和一位自由派政治家。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 112,
		"title": "“小男孩”",
		"desc": "将河内化为核废墟。并存活下来。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 113,
		"title": "从法西斯到社会主义",
		"desc": "密特朗完全实现了他的所有计划（离开欧共体并拥抱社会主义）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 114,
		"title": "回到过去",
		"desc": "法国共产党带回了无产阶级专政并保持掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 115,
		"title": "平淡的法国",
		"desc": "吉斯卡尔·德斯坦连任成功。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 116,
		"title": "戴高乐的梦想",
		"desc": "希拉克记得他的英雄（法国退出北约）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 117,
		"title": "新民主",
		"desc": "自由党和社会民主党的联盟在英国建立了新秩序。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 118,
		"title": "工党岛",
		"desc": "工党终于使英国民主化。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 119,
		"title": "老笑话",
		"desc": "英国的工党-托洛茨基主义运动分裂成了许多部分。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 120,
		"title": "克服分裂",
		"desc": "意外的盟友（托派在英国成功掌权）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 121,
		"title": "历史性妥协",
		"desc": "在意大利确实发生了！",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 122,
		"title": "莫罗的复仇",
		"desc": "莫罗背后的新势力在意大利获胜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 123,
		"title": "乱伦之果",
		"desc": "(隐藏成就)",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 124,
		"title": "历史正义",
		"desc": "科苏塔带领意大利走向更光明的未来。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 125,
		"title": "新时代共产主义",
		"desc": "因格拉奥领导意大利的社会主义进军。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 126,
		"title": "萝卜",
		"desc": "纳波利塔诺让意大利共产党面目全非。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 127,
		"title": "新欧洲",
		"desc": "法国、意大利和西班牙建立了社会主义联盟。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 128,
		"title": "二十一世纪法西斯主义",
		"desc": "阿尔米兰特带领意大利...去了哪里？",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 129,
		"title": "历史的闹剧",
		"desc": "罗穆阿尔迪复兴了意大利社会共和国的遗产。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 130,
		"title": "历史总能找到漏洞",
		"desc": "菲尼带领意大利法西斯走向终结。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 131,
		"title": "仿佛什么都没发生",
		"desc": "日本、意大利和西班牙建立了原法西斯政权，葡萄牙建立了右翼独裁，密特朗在法国获胜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 132,
		"title": "死神纪念",
		"desc": "(隐藏成就)",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 133,
		"title": "旗帜之下",
		"desc": "大阿尔巴尼亚诞生。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 134,
		"title": "狼群",
		"desc": "土耳其吞并叙利亚、伊拉克、伊朗和塞浦路斯。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 135,
		"title": "逆向安南",
		"desc": "塞浦路斯局势成功解决。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 136,
		"title": "没有祭司的新苏美尔",
		"desc": "库尔德斯坦在其最大边界内独立。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 137,
		"title": "顽强克服...",
		"desc": "民主党候选人在1980和1984年赢得美国大选。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 138,
		"title": "黑色交易",
		"desc": "(隐藏成就)",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 139,
		"title": "不可思议 2.0",
		"desc": "中国的手更长了...",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 140,
		"title": "熊的觉醒",
		"desc": "(隐藏成就)",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 141,
		"title": "折翼之鹰",
		"desc": "北约和欧共体已解散。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 142,
		"title": "珍宝岛",
		"desc": "给苏联第二个达曼斯基。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 143,
		"title": "破碎的拉斯塔法里",
		"desc": "埃塞俄比亚失去了对厄立特里亚、欧加登和提格雷的控制。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 144,
		"title": "我们过去了",
		"desc": "特赫罗政变成功。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 145,
		"title": "声明",
		"desc": "米兰斯政变成功。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 146,
		"title": "西班牙的戴高乐",
		"desc": "阿尔马达政变成功。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 147,
		"title": "新卡洛斯主义",
		"desc": "卡洛斯派新法西斯赢得了内战。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 148,
		"title": "去佛朗哥化",
		"desc": "内战巩固了苏亚雷斯的权力。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 149,
		"title": "卡洛斯-列宁主义",
		"desc": "内战巩固了共产党的权力。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 150,
		"title": "共和国的复仇",
		"desc": "内战结果：社工党掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 151,
		"title": "千年之梦",
		"desc": "加泰罗尼亚和巴斯克获得独立。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 152,
		"title": "第二次康乃馨革命",
		"desc": "左派在葡萄牙掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 153,
		"title": "新新国家",
		"desc": "右派在葡萄牙掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 154,
		"title": "三个友邦",
		"desc": "阿尔巴尼亚、南斯拉夫和罗马尼亚携手走向光明的未来。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 155,
		"title": "用自由主义打击独裁",
		"desc": "中国合并了中央条约组织(CENTO)和东南亚条约组织(SEATO)，攻击台湾并获胜。自由派朝鲜攻击韩国并获胜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 156,
		"title": "巨眼",
		"desc": "海湾合作委员会国家受中国影响。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 157,
		"title": "黑金",
		"desc": "油价达到最高（$60）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 158,
		"title": "比土还贱",
		"desc": "油价达到最低（$10）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 159,
		"title": "小罗马",
		"desc": "厄立特里亚战争拖延，罗穆阿尔迪政权利用了这一点。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 160,
		"title": "应许之地",
		"desc": "以色列采用了封建社会主义，并与玩家处于同一军事同盟。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 161,
		"title": "被背叛的革命",
		"desc": "科索拉波夫统治苏联。中国是托洛茨基国际的成员。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 162,
		"title": "划掉领袖",
		"desc": "科索拉波夫统治苏联。中国世界影响力>50.0，拥有毛主义修正且在经互会中。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 163,
		"title": "这就是辩证法",
		"desc": "科索拉波夫统治苏联。中国世界影响力<50.0或无毛主义修正。中国在经互会中。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 164,
		"title": "这回想好好搞，结果又那样",
		"desc": "科索拉波夫统治苏联。中国不在经互会。中国不在托洛茨基国际。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 165,
		"title": "走向政治流亡",
		"desc": "开启困难模式完成游戏。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 166,
		"title": "无路可退",
		"desc": "开启死亡模式完成游戏。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 167,
		"title": "幸运女神",
		"desc": "开启幸运模式完成游戏。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 168,
		"title": "改变里程碑",
		"desc": "开启政客每5年离职规则完成游戏。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 169,
		"title": "中国会变得更大",
		"desc": "开启：文革难度、死亡模式、政客每5年离职规则完成游戏。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 170,
		"title": "世界舞台的新玩家",
		"desc": "组建东亚联邦（所有可能的成员）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 171,
		"title": "新中国霸权",
		"desc": "恢复在大陆的旧有影响力。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 173,
		"title": "灾难改革",
		"desc": "在中亚击败苏联，但不进军库页岛。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 174,
		"title": "乌斯季诺夫的遗产",
		"desc": "在中亚和库页岛击败苏联。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 175,
		"title": "缅甸的命运",
		"desc": "在联邦中实现该国4种可能命运中的任何一种。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 176,
		"title": "泰国的命运",
		"desc": "在联邦中实现该国4种可能命运中的任何一种。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 177,
		"title": "老挝的命运",
		"desc": "在联邦中实现该国4种可能命运中的任何一种。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 178,
		"title": "越南的命运",
		"desc": "在联邦中实现该国4种可能命运中的任何一种。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 179,
		"title": "柬埔寨的命运",
		"desc": "在联邦中实现该国4种可能命运中的任何一种。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 180,
		"title": "日本皇室的命运",
		"desc": "在联邦中实现该国4种可能命运中的任何一种。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 181,
		"title": "食人者",
		"desc": "东亚联邦所有国家均为威权主义（灰色）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 182,
		"title": "强力战队",
		"desc": "东亚联邦所有国家均为社会主义（红色）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 183,
		"title": "吸烟有害健康",
		"desc": "东亚联邦所有国家均为改革派（绿色）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 184,
		"title": "新门面",
		"desc": "东亚联邦所有国家均为自由派（蓝色）。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 185,
		"title": "激活红色基因",
		"desc": "按下相应的决议。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 186,
		"title": "泛世界野餐",
		"desc": "奥匈帝国、南斯拉夫、普鲁士、罗马尼亚、捷克斯洛伐克和中国接受了新秩序。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 187,
		"title": "奥地利的复仇",
		"desc": "约瑟夫·里格勒在独立的奥地利成功掌权。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 188,
		"title": "匈牙利社会主义道路",
		"desc": "采纳博尔贝伊的计划。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 189,
		"title": "新萨拉希主义",
		"desc": "采纳基谢利的计划。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 190,
		"title": "球进啦！",
		"desc": "奥匈帝国重组。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 191,
		"title": "东欧的法国",
		"desc": "米洛舍维奇获胜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 192,
		"title": "哈哈镜王国",
		"desc": "舍舍利获胜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 193,
		"title": "兰科维奇归来",
		"desc": "乔西奇获胜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 194,
		"title": "解放神学",
		"desc": "自由左翼胡斯派实现目标。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 195,
		"title": "上帝之国",
		"desc": "保守右翼胡斯派实现目标。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 196,
		"title": "革新主义",
		"desc": "捷克斯洛伐克走上教会改革之路。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 197,
		"title": "斯大林之手",
		"desc": "格奥尔基·阿波斯托尔恢复了在罗马尼亚的旧有角色。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 198,
		"title": "共青团国王",
		"desc": "罗马尼亚建立了社会主义君主制。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 199,
		"title": "白猫黑猫都是鹰",
		"desc": "市场在东德获胜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 200,
		"title": "黑色阵线",
		"desc": "普鲁士重返世界舞台。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 201,
		"title": "“康尼”，自己人",
		"desc": "瑙曼让统一社会党回归现实。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 202,
		"title": "救国阵线",
		"desc": "格奥尔基·阿波斯托尔掌权。戈尔巴乔夫/利加乔夫掌权。中国不在经互会，但国力>60.0。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 203,
		"title": "重新定位",
		"desc": "格奥尔基·阿波斯托尔掌权。戈尔巴乔夫/利加乔夫掌权。中国不在经互会，且国力<60.0。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 204,
		"title": "酸汤共产主义",
		"desc": "“知识分子集团”掌权。经互会成员少于15个。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 205,
		"title": "南斯拉夫邦联",
		"desc": "舍舍利失败。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 206,
		"title": "激进铁托主义",
		"desc": "多兰茨获胜。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 207,
		"title": "铁托重生",
		"desc": "多兰茨失败。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 208,
		"title": "白手起家",
		"desc": "让普通公民从政。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 209,
		"title": "人民公仆",
		"desc": "任命公民为部长。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 210,
		"title": "众望所归",
		"desc": "公民成为统治者。",
		"icon": "",
		"source": "AchievementData",
	},
	{
		"number": 211,
		"title": "人民革命",
		"desc": "公民因动乱上台掌权。",
		"icon": "",
		"source": "AchievementData",
	},
]



## 按编号查找成就展示数据；找不到返回空字典。
static func find(number: int) -> Dictionary:
	for item in LIST:
		if int(item["number"]) == number:
			return item
	return {}


## 获取成就图标资源路径：优先条目里的 "icon"，其次按成就编号找 资产/成就/<编号>.png，最后用默认图标。
static func icon_path(number: int) -> String:
	var item := find(number)
	if item.has("icon") and str(item["icon"]) != "":
		return str(item["icon"])
	var direct := "res://资产/成就/%d.png" % number
	if ResourceLoader.exists(direct):
		return direct
	return DEFAULT_ICON


## 已解锁计数（UI 标题用）。
static func unlocked_count() -> int:
	var n := 0
	for item in LIST:
		if Achievements.is_unlocked(int(item["number"])):
			n += 1
	return n
