# 项目架构优化方案（人工可读版）

> 面向：后续接手的开发者与维护者
> 依据：2026-08-16 对 `中国-毛的遗产[dh-4591]` 工程的实际读码与全量扫描
> 原则：**先对齐原版行为，再谈结构优化**；所有优化必须“不改变游戏数值/文案/顺序”，并以可回滚的小步提交推进。

---

## 1. 现状事实（接手项目前先看这一节）

### 1.1 规模快照

| 项目 | 数值 |
|---|---|
| GDScript 文件 | 580 个（场景 51 + 数据脚本 528 + 根脚本） |
| GDScript 总行数 | 约 3.56 万行（场景约 2.13 万 + 数据脚本约 1.43 万） |
| 场景文件 | 25 个 .tscn |
| 事件资源 | 531 个 `.tres`（`场景/事件界面/events/`） |
| 事件效果脚本 | 482 个（`数据脚本/事件效果/`） |
| 全局类 | 47 个 `class_name` |
| 静态函数 | 453 个 `static func` |
| Autoload | 4 个：GameManager、EventEngine、Achievements、音频总管 |
| 资产文件 | 约 901 个 |

### 1.2 核心文件与职责

| 文件 | 行数 | 现状职责 |
|---|---|---|
| `数据脚本/game_manager.gd` | 3333 | 设置、时间 tick、事件调度、科技、政变、经济/政治双周结算、存档读档 |
| `场景/外交界面/国家面板.gd` | 2634 | 国家面板显示 + 逐国数字 + 一批外交动作定义 |
| `场景/外交界面/国家面板_逐国链.gd` | 2333 | 逐国链按钮的 38 个函数、约 864 个显示槽位 |
| `场景/外交界面/外交互动_批1..6.gd` | 8175（合计） | 34/34/34/34/31/46 个 `_def_N` 动作定义 |
| `数据脚本/decision_atoms.gd` | 1786 | 决议条件/效果原子库 |
| `数据脚本/world_factory.gd` | 1608 | 新游戏世界构建、国家/人物/派系/修正初始化 |
| `数据脚本/event_engine.gd` | 910 | 事件扫描、触发评估、EffectNode 执行、自定义脚本调用 |
| `数据脚本/world_state.gd` | 777 | 数据模型 + 领域逻辑 + 展示映射 + 经济视图同步 |

### 1.3 三条主干链路（新增功能前必须理解）

1. **时间循环**：`GameManager._process` 按速度累计 → `tick()` 推进一天 →
   - 日块：赤字恢复、科研点、政治路线、体制重算、每周盟友维护
   - 月块：`_on_month_changed()`（人口、寡头、外援）
   - 双周块：`_on_fortnight()` 内**按原版 TimeScript 行序硬编码调用约 26 个 `_fortnight_*` 函数**，最后 `FocusSystem.tick()`、`WAR_SYS.fortnight_wars()`、`_check_endings()`
   - tick 末尾：`clamp_values → mirror_empires → sync_economy → date_changed/stats_changed → 自动存档`
   - **顺序即业务规则**：任何调整结算顺序都等于改游戏数值。
2. **事件流**：`EventEngine._scan_events()` 扫描 `.tres` → `check_and_fire()` 评估 `ExprNode` 条件 → 触发时 `execute(Array[EffectNode])`，`CUSTOM_SCRIPT` 效果调用事件效果脚本的 `execute()`。
3. **存档流**：`ResourceSaver.save(world, "user://saves/save_XX.res")` 直接序列化整个 `WorldState` + 槽位摘要 `meta.json`；读档时靠 `load_game()` 里的**手工补丁式迁移**（科技数组 `ensure_size()`、重建 gwcode 索引、RNG 续流、EventEngine 运行时导入）。

---

## 2. 已确认的问题清单

### 2.1 结构与耦合问题

**P0-1：GameManager 是 God Object。**
`game_manager.gd` 3333 行、130 个函数，同时承担门面、调度器、经济系统、政治系统、科技系统、存档系统六种职责。双周结算顺序散落在 `_on_fortnight()` 的 26 个调用里，新机制必须插进这个隐式流水线，改动面与回归风险都很高。

**P0-2：WorldState ↔ EventEngine 存在依赖环。**
- `world_state.gd:498/507` 的数据模型方法反向查询 `EventEngine.event_done_by_number(...)`；
- `event_engine.gd:117/126` 又读 `GameManager.world`。
- 结果：数据层、运行时层、单例层三方互相依赖，改存档结构或事件注册表会连环影响。

**P0-3：事件效果脚本有大量逐字重复（本次已用脚本逐字节比对确认）。**
| 函数 | 定义数量 | 与基类完全一致 | 变体 |
|---|---|---|---|
| `func _add(index, delta)` | 287 | **287 / 287 全部一致** | 0 |
| `func _country(idx)` | 55 | 基类没有该函数；55 份互相一致 | 1 种 |
| `func _leave_alliances(c)` | 59 | 5 份一致 | 6 种（tag 列表差异，需逐变体审计是否等同原版语义） |

- `_add` 与 `_country` 可直接消除（前者删掉即可用基类，后者上提到基类后删除 55 份）。
- `_leave_alliances` 的 6 种变体差异在“清哪些联盟 tag”，必须对照原版 `Country.LeaveAlliances()` 逐项裁决，不能盲删。
- 另有 151 个事件脚本在基类已经提供 `ws/d` 成员的情况下仍直接引用 `GameManager`。

**P1-1：外交交互是 1.06 万行过程式代码。**
`国家面板` + `逐国链` + `批1-6` 合计约 10600 行，结构是 `if sid == N:` / `_def_N()` 大链。改一个国家要跨多个文件登记；新增按钮需要在“逐国链显示槽位、批文件定义、目录分发”三处同步。既不利于阅读，也容易再犯我们刚修过的“少一个 `conds.append`、少一个括号”类错误。

**P1-2：UI 直接拉全局状态。**
32 个场景脚本直接引用 `GameManager`，`GameManager.world` 被 177 处代码直接访问。6 个状态栏脚本（事件/外交/战争/概览/派系/经济）是近似拷贝。已有 `stats_changed/date_changed/world_state_loaded` 信号，但使用不统一（有的 `_refresh` 兜底、有的 deferred rebuild）。

**P1-3：魔法字符串与裸索引。**
- `has_tag/set_tag/get_flag/set_flag` 等字符串调用约 3720 处（`"亲中"`、`"sev"`、`"nato"`…）；
- 直接读写 `数值表[i]` 约 1714 处；虽然有 97 个 `W.I_*` 索引常量，但语义访问器（`get_data_value/set_data_value/add_data_value`）没有被强制使用；
- tag 拼写错误、文案粘贴错误不会在编译期暴露，只能靠人工或运行时发现。

### 2.2 可维护性问题

- **无自动化回归测试**：项目只有 `tmp/batch3_ranges.txt` 这类静态自检残留，和“改完靠编辑器人工验证”的流程。3.56 万行、tick 顺序敏感的模拟器没有黄金样本，重构相当于蒙眼拆弹。
- **静态可变状态**：453 个 `static func`，多个 Catalog 用 `static var _cache/_by_id/_loaded`，`new_game/load_game/reload` 时靠各模块自觉清缓存，缺少统一的 `reset_all()` 注册机制。
- **数据类承担业务**：`WorldState` 777 行里既有 @export 数据，也有 `is_socialism/can_found_african_union` 等规则、`display_meter/display_relation` 等展示逻辑、`flush_economy/结算两周变化` 等结算逻辑。
- **事件双轨制**：531 个资源 + 482 个脚本。事件定义在资源里，特殊逻辑在脚本里，加一个事件常常要两边都动；`ExprNode/EffectNode` DSL 已经存在但覆盖面不足，导致“本可以纯数据”的事件也写了脚本。

---

## 3. 目标架构（分层与依赖规则）

### 3.1 目标分层

```
┌─────────────────────────────────────────────────────────────┐
│ L4 表现层  场景/*.tscn + 场景/*.gd                            │
│            只订阅信号；只调用 L3 门面 API；不直接摸 WorldState │
├─────────────────────────────────────────────────────────────┤
│ L3 编排层  GameManager（薄门面）+ GameSession                  │
│            拥有 WorldState 实例；排 tick 顺序；存档/读档；      │
│            把事件/时间信号广播给 L4                            │
├─────────────────────────────────────────────────────────────┤
│ L2 领域服务  EconomyService / PoliticsService / TechService    │
│            WarSystem / PoliticianSystem / FocusSystem         │
│            DecisionSystem / SaveService                       │
│            函数显式接收 WorldState，禁止引用 autoload           │
├─────────────────────────────────────────────────────────────┤
│ L1 内容目录  EventCatalog / WarCatalog / ModifierCatalog       │
│            DecisionCatalog / FocusCatalog / DiplomacyCatalog  │
│            只做“定义查找与加载”，不写 tick 逻辑                │
├─────────────────────────────────────────────────────────────┤
│ L0 领域模型  WorldState / CountryData / PoliticianData         │
│            FactionData / EmpireData / WarData / GameDate       │
│            Tag/Flag 常量表；纯数据 + 不变量校验                 │
└─────────────────────────────────────────────────────────────┘
```

### 3.2 依赖规则（写进代码评审规范）

1. **只向下依赖**：L4 → L3 → L2/L1 → L0；禁止 L0/L1/L2 引用 autoload（GameManager/EventEngine/Achievements/音频总管）。
2. **数据模型不反向查询运行时**：L0 不 import EventEngine；事件完成/结果先由 EventEngine 在“导入阶段”写进 WorldState 自己的字段，之后 L0 自给自足。
3. **所有 tick 步骤显式列在 TickPipeline**：每个步骤有编号、名称、原版 TimeScript 行号注释、前置/后置条件；步骤之间不互相直接调用。
4. **UI 只读不写**：所有世界修改必须经过 L3 门面的具名方法（如 `apply_policy_change`），禁止 UI 里 `world.数值表[...] +=`。
5. **内容用资源/数据，不用代码分支**：能进 `.tres`/JSON 的条件和文案不进代码。

### 3.3 目标目录（迁移后形态，仅作蓝图）

```
数据脚本/
  domain/            # L0：WorldState、CountryData 等（逐步迁入）
  services/          # L2：economy/politics/tech/tick_pipeline/save
  catalogs/          # L1：event/war/modifier/decision/focus/diplomacy
  events/
     resources/      # 事件 .tres（对应现在 场景/事件界面/events/）
     scripts/        # 事件效果脚本
  tags.gd            # 所有 tag/flag 的 StringName 常量（唯一权威）
  data_indices.gd    # 数值表索引语义访问器（配合 WorldState）
场景/
  ui/                # 共享 UI 基类与通用组件（状态栏、按钮、tooltip）
  外交界面/ ...
```

> 目录迁移属于最后阶段，且必须成批更新 `preload/extends/res://` 引用；在迁移完成前，先按“旧文件变薄、新文件接管”的方式过渡。

---

## 4. 人工可读性规范（后续开发者上手门槛）

### 4.1 文件头模板（每个 .gd 必写）

```gdscript
## <文件职责，一句话>
## 对齐原版：<Unity 文件与行号，无则写“原创/数据驱动”>
## 依赖：<只列直接依赖的全局类/autoload；违反分层要写 TODO>
## 修改：
##   2026-08-16  <改动一句话，含原因>
```

### 4.2 规模预算（超过就要拆分，不追求“写完就行”）

| 类型 | 建议上限 |
|---|---|
| 单个 .gd | 800 行（现有超限文件必须拆或数据化） |
| 单个函数 | 60 行（`_def_N` 类动作定义除外） |
| 事件效果脚本 | 200 行，且只允许 `prepare/execute` + 私有显示文案 |
| 单个 Catalog | 400 行；超过就要考虑资源化 |

### 4.3 命名与常量

- 保留现有中文领域命名（`数值表/原版序号/亲中` 与原版一一对应，是追溯资产，不强行英文化）。
- **新增代码统一英文命名**（services/catalogs 用英文类名），中文只用于领域字段与注释。
- 所有 tag/flag 收敛到 `tags.gd` 的 `StringName` 常量，例如：

```gdscript
class_name Tags
const 亲中 := &"亲中"
const SEV := &"sev"
const NATO := &"nato"
```

- 数值表索引禁止裸数字；优先用 `WorldState.I_*` 常量，复杂读取统一走语义访问器。

### 4.4 注释纪律

- 凡是“为什么和原版不一样”必须写注释；本次修复的括号/续行/遮蔽问题都源于“译文与源码之间没有解释”。
- 每个 tick 步骤保留 `# TimeScript.cs:行号` 溯源注释，重构时逐行搬运，不得丢弃。

---

## 5. 分阶段实施路线

> 每阶段独立提交、可回滚；每阶段完成后只做静态自检 + 主人在编辑器里验证（遵守“不跑 headless 验证”约定）。

### 阶段 0：静态自检与文档基线（1 个改动点）
- 把 UTF-8 严格扫描、括号平衡、重复 `class_name`、tag 字符串白名单审计、helper 覆盖比对写成 `工具/检查/*.js`（或 GD 自检脚本），纳入仓库。
- 产出本方案文档与“文件职责清单”（附录 B）。
- 验收：工具对当前代码跑出 0 个结构性错误；文档与代码一致。

### 阶段 1：零行为变化清理（优先做，风险最低）
1. **事件脚本去重**：
   - 删除 287 份与基类逐字节一致的 `_add`；
   - 把 55 份一致的 `_country` 上提到 `event_script_base.gd`，删除子类定义；
   - 对 `_leave_alliances` 的 6 个变体逐个对照原版裁决，统一为基类或明确注释差异。
2. **建立 tag/flag 常量表**：先只建表 + 试点替换一个目录（例如 `数据脚本/事件效果`），编译通过后再逐步扩大。
3. **状态栏去重**：抽 `GameUIStatusBar` 基类或一个共用组件，六个状态栏场景只保留各自差异字段。
4. **WorldState 与 EventEngine 解耦**：把“EventEngine 注册表回退”逻辑移到 EventEngine 的 import 阶段；WorldState 的 `event_done_num/result_of_event_num` 只读自身数据。
5. **存档版本字段**：`WorldState.save_version` + 一个集中式 `SaveMigration`，现有 `ensure_size()` 等零散迁移收拢进去。
- 验收：静态自检通过；编辑器跑一局“开局 → 推 1 年 → 读档”数值一致（人工比对）。

### 阶段 2：GameManager 拆分（一次一个服务）
1. 先抽 **TickPipeline**：把 `_on_fortnight()` 的 26 个调用变成带注释的步骤数组，不改变顺序。
2. 再抽 **EconomyService**：把 `_daily_* / _monthly_* / _fortnight_*` 中与经济相关的函数原样搬成 `static func`（参数仍是 `d, w`），GameManager 只做调用。
3. 接着抽 **PoliticsService / TechService / SaveService**。
4. 最后 GameManager 只保留：世界实例、公开 API、场景/信号协调。
- 验收：每个服务搬完跑一次自检 + 编辑器人工验证；GameManager 降到 800 行以内。

### 阶段 3：内容数据化
1. **外交动作资源化**：定义 `DiploActionDef` Resource（caption/opis/conditions/effects/dormant），把批 1-6 的常规动作迁到 `资产/数据/外交/*.tres`；批文件只保留加载器与特殊分支。目标：批文件从 8175 行降到 2000 行以内。
2. **事件 DSL 覆盖**：扩充 `EffectNode/ExprNode` 类型，让“加资源/改 tag/改国家字段/开战”等常规事件全部资源化；事件脚本数量从 482 降到只保留动态文案与复杂分支。
3. **拆分国家面板**：`国家面板.gd` 按“通用面板 / 逐国数字 / 特殊按钮”拆成 3-4 个文件，每个不超过 800 行。

### 阶段 4：分层目录迁移 + 测试基线
1. 按 3.3 的目标目录迁移文件，用脚本全量替换 `res://` 引用并在编辑器里做一次全量导入。
2. 建立编辑器内自检场景：固定开局 → 推进 N 个双周 → 导出数值表快照，与人工确认的基准对比。
3. 把事件/决议/外交内容的生成器（如果保留生成模式）纳入仓库，并记录生成物与生成源的对应关系。

---

## 6. 风险与兼容

| 风险 | 对策 |
|---|---|
| 改动 tick 顺序改变数值 | 阶段 1-2 只搬家不排序；每步保持函数调用顺序逐字一致 |
| 删除事件 helper 改变行为 | 只删逐字节一致项；变体项先对原版裁决再动 |
| 存档不兼容 | 引入 `save_version` + 集中迁移；旧档只做“读入补齐”，不重排字段 |
| 丢失原版溯源注释 | 搬家时注释随函数整块搬运，评审时检查 `TimeScript.cs:` 行号 |
| 中文路径/文件名在工具链出问题 | 目录迁移放在最后阶段，先小范围试点（一个目录），成功再扩大 |
| 无自动化测试导致回归 | 阶段 0 先落地静态自检；阶段 4 再补编辑器内快照对比 |

---

## 7. 开放问题（需要主人拍板）

1. 是否允许未来在仓库里放一个**编辑器内自检场景**（不是 headless，是在 Godot 编辑器里手动运行、打印通过/失败）？
2. `_leave_alliances` 的 6 个变体里，有 3 个 tag 列表不一样（是否原版本身就有版本差异？）——需要以原版 `Country.cs` 为准逐项裁决，确认后我再动手。
3. 目录迁移是否接受“先在新目录建文件、旧文件保留为薄代理”的过渡期，而不是一次性移动？
4. 新增代码是否强制英文命名、领域字段保留中文？（建议：是）

---

## 附录 A：本次审计数据快照（2026-08-16）

- 580 个 .gd，约 3.56 万行
- `game_manager.gd` 3333 行 / 130 函数
- 外交动作文件合计约 10600 行
- 事件 `.tres` 531 / 效果脚本 482
- `GameManager.world` 直接访问 177 处；数值表直接读写约 1714 处；tag/flag 字符串调用约 3720 处
- 事件 helper 重复：`_add` 287/287 与基类一致；`_country` 55/55 互相一致；`_leave_alliances` 6 种变体

## 附录 B：后续开发者必读文件顺序

1. `数据脚本/game_manager.gd` → `tick()` / `_on_fortnight()`（时间顺序）
2. `数据脚本/event_engine.gd` → `check_and_fire()` / `execute()`（事件 DSL）
3. `数据脚本/world_state.gd` → 数据模型与访问器
4. `场景/外交界面/外交互动_基础.gd` → 外交动作公共翻译层
5. `数据脚本/world_factory.gd` → 开局世界如何被构造
6. 本方案文档 → 修改前的架构约束
