extends EventScriptBase

## 自动迁移自 场景/事件界面/events/event_014_budget_crisis.tres
## 文案见 资产/本地化/events_zh_CN.csv

const META := {
	"id": "budget_crisis",
	"num": 14,
	"notify": false,
	"once": false,
	"trigger": [{"t": "ALL", "c": [{"t": "RESOURCE_SUM_AT_MOST", "v": 799, "keys": ["money", "budget_army", "budget_mgb", "budget_science", "budget_admin", "budget_envelope", "budget_propaganda", "budget_agriculture", "budget_industry", "budget_services", "budget_welfare", "budget_diplomacy"]}, {"t": "RESOURCE_AT_MOST", "key": "money", "v": 299}]}],
	"options": [{"result": true, "fx": [{"t": "ADD_RESOURCE", "key": "people_support", "v": -100}, {"t": "ADD_RESOURCE", "key": "thought_freedom", "v": 50}, {"t": "ADD_RESOURCE", "key": "money", "v": 100}, {"t": "ADD_RESOURCE", "key": "living", "v": -300}]}, {"disabled": true, "result": true, "cond": {"t": "RESOURCE_AT_LEAST", "key": "economy_system", "v": 14}, "fx": [{"t": "ADD_RESOURCE", "key": "money", "v": 100}, {"t": "ADD_RESOURCE", "key": "party_support", "v": -500}, {"t": "ADD_RESOURCE", "key": "thought_freedom", "v": 300}, {"t": "ADD_EMPIRE_RELATION", "key": "0", "v": -50}, {"t": "ADD_RESOURCE", "key": "oligarch", "v": -5}]}, {"disabled": true, "result": true, "cond": {"t": "ANY", "c": [{"t": "EMPIRE_RELATION_AT_LEAST", "key": "0", "v": 501}, {"t": "ALL", "c": [{"t": "EMPIRE_RELATION_AT_LEAST", "key": "1", "v": 501}, {"t": "RESOURCE_AT_LEAST", "key": "influence_prc", "v": 50}]}, {"t": "NOT", "c": [{"t": "ANY", "c": [{"t": "ALL", "c": [{"t": "RESOURCE_AT_LEAST", "key": "economy_system", "v": 13}, {"t": "RESOURCE_AT_LEAST", "key": "living", "v": 500}]}, {"t": "RESOURCE_AT_LEAST", "key": "economy_system", "v": 14}, {"t": "ALL", "c": [{"t": "RESOURCE_AT_MOST", "key": "economy_system", "v": 14}, {"t": "RESOURCE_NOT_EQUALS", "key": "political_line"}, {"t": "ANY", "c": [{"t": "RESOURCE_AT_LEAST", "key": "party_system", "v": 8}, {"t": "RESOURCE_NOT_EQUALS", "key": "political_line", "v": 1}]}]}]}]}]}, "fx": [{"t": "ADD_RESOURCE", "key": "money", "v": 100}, {"t": "ADD_RESOURCE", "key": "loan", "v": 100}, {"t": "ADD_RESOURCE", "key": "influence_prc", "v": -50}]}, {"disabled": true, "result": true, "cond": {"t": "ALL", "c": [{"t": "RESOURCE_AT_MOST", "key": "economy_system", "v": 14}, {"t": "RESOURCE_NOT_EQUALS", "key": "political_line"}, {"t": "ANY", "c": [{"t": "RESOURCE_AT_LEAST", "key": "party_system", "v": 8}, {"t": "RESOURCE_NOT_EQUALS", "key": "political_line", "v": 1}]}]}, "fx": [{"t": "ADD_RESOURCE", "key": "living", "v": -100}, {"t": "ADD_RESOURCE", "key": "money", "v": 100}, {"t": "ADD_RESOURCE", "key": "industry", "v": -50}, {"t": "ADD_RESOURCE", "key": "agriculture", "v": -50}, {"t": "ADD_RESOURCE", "key": "services", "v": -50}, {"t": "ADD_RESOURCE", "key": "oligarch", "v": 20}, {"t": "SET_RESOURCE", "key": "economy_system", "v": 13, "if": {"t": "RESOURCE_AT_MOST", "key": "economy_system", "v": 12}}]}],
}
